### ISSUE TITLE
RIS Footer

### ISSUE THREAD

**Issue by gjhuerte** [gjhuerte/sims#103]
No RIS Information....

**Comment by gjhuerte** [comment]
Did you revert it or does it still remain as nothing?

**Comment by imyunotme** [comment]
What do you mean by no RIS Information?

**Comment by gjhuerte** [comment]
When we presented the last time, the footer of printables of RIS has no information: no names, nothing. I ask if its inserted or Sir Carlo decided to removed it.

**Comment by imyunotme** [comment]
Sir decided to remove it until the office are fixed.
