### ISSUE TITLE
Problems to be fixed

### ISSUE THREAD

**Issue by imyunotme** [gjhuerte/sims#108]
1. Updating of new office officials
2. RIS Format. (header and signatories should be constant on all pages. )
3. Note why the request was cancelled and who received the request
4. Database side of the internet version. // can't insert, edit, delete due to the table it was looking for starts with a capital letter.
5. Separation of roles:
 >Property Inventory and Disposal Section
--Disposal
>Supply Inventory Section
--Accepting user
>University Store room
--Releasing user

**Comment by gjhuerte** [comment]
Can you please separate it in individual issue so that we can track each issue. Thanks

**Comment by gjhuerte** [comment]
Please specify the number 4 issue. What specific table or module does it affects. Who is the user? What do you mean by database side?

**Comment by gjhuerte** [comment]
You can add additional officials and remove others. Is there a problem with it?

**Comment by gjhuerte** [comment]
Is the database fixed? Are the users properly assigned to their office so that we can include the header and signatories?

**Comment by gjhuerte** [comment]
Regarding who received the request. We did not include it. It can affect our database. We focuses on approval and releasing only. This might cause an issue if not properly placed on the system. This will take time. Regarding Cancellation, there is also a remarks field before you can cancel a request, am I wrong? I've already added that a long time ago

**Comment by imyunotme** [comment]
Pardon the title, with regards to Prob. 1 there will be a meeting for the BOR in march 16 so there will be reorganizing again the office officials. It's not a problem. Sorry for including it. As for prob 2 can you please do it? the the parts from Purpose and below should be in all pages. And they are asking if we can change the page size to Short. So there will only be 15-17 rows per page i guess. For Prob 3 I made the cancellation details mandatory and for the received by i utilized the remarks since its not used if the request is approved. We needed only a reference for who received the item. Now prob 4, the sad part, In theory we(sir adi) think that is has to do with the database engine they are using. For the affected module, all module with insert and update function are affection. ICTO advised to follow the naming convention of using a capitalized table name, but for now i will prioritize checking the modules for requesting so branches can use it by next week. Finally yeah i should have separated it. 
i will separate the issues that haven't been fixed yet.
