### ISSUE TITLE
[ Request ] Only Available Items when Searching

### ISSUE THREAD

**Issue by imyunotme** [gjhuerte/sims#112]
Offices are request if we could hide or remove in the list of search items the stock that is in their critical level or no more items?

**Comment by imyunotme** [comment]
Solution A: Disable/Hide the Select button so that the item is still viewable by the users
Solution B: Hide the item it entirely
Solution C: do you have a better one?

Solution A is approved by sir Carlo and Ma'am Canlas

**Comment by gjhuerte** [comment]
Solution A is good but the main problem is that the form is used by more than 1 module.
