### ISSUE TITLE
RSMI Generation

### ISSUE THREAD

**Issue by imyunotme** [gjhuerte/sims#113]
it generates all RIS. It should only be the RIS for that month, Although it does not include the RIS of the next months only the previous months

**Comment by imyunotme** [comment]
A misunderstanding. it includes the RIS base on its released date. I am now clarifying this with PSMO

**Comment by gjhuerte** [comment]
please confirm this

**Comment by gjhuerte** [comment]
Close this issue if its ok @imyunotme
