### ISSUE TITLE
Datatables Error in Accounting>References

### ISSUE THREAD

**Issue by imyunotme** [gjhuerte/sims#21]

**Comment by gjhuerte** [comment]
Duplicate of [https://github.com/gjhuerte/sims/issues/22](url)

**Comment by gjhuerte** [comment]
Possible Duplicate of [https://github.com/gjhuerte/sims/issues/22](url)

**Comment by gjhuerte** [comment]
Duplicate of [https://github.com/gjhuerte/sims/issues/22](url)
