### ISSUE TITLE
1/15/18 issues

### ISSUE THREAD

**Issue by imyunotme** [gjhuerte/sims#9]
Server:
>time is incorrect. possibility of an incorrect timezone set

AMO side
>Entity name is missing in stockcard view
>advanced search. error 404
>RIS no. generation. counter should resets every month

**Comment by gjhuerte** [comment]
issuance slip generation reset is not possible unless you removed all the issuance slip from the database. Uses the ID of requests as the last part of code

constant - month - year - id
